apiVersion: skaffold/v1beta15
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*

build:
  local:
    push: false

  artifacts:
    ########### client
    - image: vastlyblank/ui
      context: ui
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "src/**/*.js"
            dest: .
    ########### posts
    - image: vastlyblank/posts
      context: post
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .

    ########### comments
    - image: vastlyblank/comments
      context: comment
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .

    ########### query service
    - image: vastlyblank/query-service
      context: query_service
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    ########### moderation
    - image: vastlyblank/moderation
      context: moderation
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
    ###########  event bus
    - image: vastlyblank/event-bus
      context: event-bus
      docker:
        dockerfile: Dockerfile
      sync:
        manual:
          - src: "*.js"
            dest: .
